notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
  #downstream:
    #server: $$DOWNSTREAM_DRONE_SERVER
    #repositories:
      #- jbaptiste_cs/ctecsas-mconf-web
      #- jbaptiste_cs/apukay-mconf-web
    #token: $$DOWNSTREAM_DRONE_TOKEN
    #when:
      #event: push
      #branch: master
      #success: true
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/mconf-web
    tag:
      - latest
    file: mconf/Dockerfile
    context: mconf
    load: docker/image-mconf.tar
    save:
      destination: docker/image-mconf.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  #Temporal fix while running on CentOS
  #storage_driver: vfs
  cache:
    mount:
      - docker/image-mconf.tar
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/mconf-mariadb
    tag:
      - latest
    file: mariadb/Dockerfile
    context: mariadb
    load: docker/image-mariadb.tar
    save:
      destination: docker/image-mariadb.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  cache:
    mount:
      - docker/image-mariadb.tar
