mconf:
  build: mconf
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
  expose:   
#   ports:
  - "80:80"
  links:
  - mariadb:mariadb
  - postfix:postfix
  - redis:redis
  - bbb:bbb
#   volumes:
# # If you want to run the installer, uncomment this:
  environment:
#      MCONF_INSTALL: "yes"
      MCONF_DB_PASSWORD: changeme
      MCONF_ADMIN_USERNAME: root
      MCONF_ADMIN_PASSWORD: changeme
      MCONF_ADMIN_EMAIL: admin@example.com
      MCONF_ADMIN_NAME: "Admin"
#      MCONF_SITE_NAME: ""
      MCONF_SITE_DESC: ""
#      MCONF_SITE_NAME: ""
#      MCONF_SITE_LOCALE: "es-419"
      MCONF_SITE_DOMAIN: "meet.example.com"
#       MCONF_SITE_FEEDBACK_URL: ""
#       MCONF_SITE_ANALYTICS_CODE:
#       MCONF_SITE_SMTP_SERVER:
#       MCONF_SITE_SMTP_PORT:
      MCONF_SITE_SMTP_DOMAIN: "example.com"
      MCONF_SITE_SMTP_SENDER: "noreply@example.com"
#       MCONF_SITE_SMTP_USE_TLS:
#       MCONF_SITE_SMTP_AUTO_TLS:
#       MCONF_SITE_SMTP_AUTH_TYPE:
#       MCONF_SITE_SIGNATURE:
#       MCONF_SITE_SSL:
      MCONF_WEBCONF_NAME: "bbb"
#      MCONF_WEBCONF_SERVER: "bbb.example.com"
      MCONF_DISABLE_REGISTRATION: "yes"
#      MCONF_WEBCONF_VERSION: 0.8
      VIRTUAL_HOST: meet.example.com
  privileged: true
mariadb:
  build: mariadb
  expose:
  - "3306"
  volumes:
  - /var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: changeme
postfix:
   image: juanluisbaptiste/postfix:latest
   expose: 
   - "25"
   env_file: credentials-smtp.env
redis:
   image: redis:latest
bbb:
  image: juanluisbaptiste/bigbluebutton:latest
  expose:
  - "80:80"
# ports: 
  - "9123:9123"
  - "1935:1935"
  environment:
     SERVER_NAME: bbb.example.com
     SERVER_SALT: 5ca422de042242086336aa041f26d79e
     VIRTUAL_HOST: bbb.example.com
# proxy:
#   image: juanluisbaptiste/bigbluebutton-proxy:latest
#   #build: nginx/
#   ports: 
#     - "80:80"
#   volumes:
#     - /var/run/docker.sock:/tmp/docker.sock  
data:
  #build: wwwdata/
  image: ubuntu:14.04
  volumes:
  - /var/lib/mysql
#   - /var/bigbluebutton
#   - /var/freeswitch
#   - "mconf/backups:/data/backups"
  command: /bin/true
bbbdata:
  #build: wwwdata/
  image: ubuntu:14.04
  volumes:
  - /var/bigbluebutton
